# Generated by Django 5.0.4 on 2024-04-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_year', models.IntegerField()),
                ('movie_director', models.CharField(max_length=255)),
                ('movie_rating', models.FloatField()),
                ('movie_banner', models.ImageField(upload_to='movies/')),
                ('movie_url', models.URLField()),
                ('movie_description', models.CharField(max_length=500)),
                ('movie_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_movie.genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movies',
            },
        ),
    ]
